version: 2.1

executors:
  dotnet-circleci:
    docker:
      - image: codekinson/dotnet-circleci:preview
    working_directory: ~/project

jobs:
    build:
        executor: dotnet-circleci
        steps:
            - checkout
            - run: 
                name: Build
                command: dotnet build --configuration ${CONFIGURATION}
            - persist_to_workspace:
                root: /
                paths:
                    - .nuget
                    - project/test
                    - project/src
                    - project/*.sln

    test:
        executor: dotnet-circleci
        steps:
            - attach_workspace:
                at: .
            - run: 
                name: Run Tests
                command: dotnet test --configuration ${CONFIGURATION} --no-build --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            - run: 
                name: Convert Test Results
                command: |
                    mkdir -p ~/junit
                    trx2junit --output ~/junit/xUnit test/*.*Tests/TestResults/*.trx
            - run:
                name: Upload Code Coverage Report
                command: |
                    curl -s https://codecov.io/bash > codecov
                    chmod +x codecov
                    ./codecov -t "${CODECOV_TOKEN}"
            - store_test_results:
                path: ~/junit

    pack:
        executor: dotnet-circleci
        steps:
            - attach_workspace:
                at: /
            - run:
                name: Create Artifacts Directory
                command: mkdir -p /project-artifacts
            - run:
                name: Pack
                command: dotnet pack --configuration ${CONFIGURATION} --no-build --output /project-artifacts
            - store_artifacts:
                path: /project-artifacts

workflows:
    version: 2
    build_preview:
        jobs:
            - build
            - test:
                requires:
                    - build
            - pack:
                requires:
                    - test
